name: Go CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

  lint:
    name: Run Linter (golangci-lint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
          ./bin/golangci-lint run || exit 0  # avoid fail build kalau warning

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "📦 Pulling latest code..."
            cd /root/kasir-api-go
            git pull origin main

            echo "📌 Setting Go 1.22 path..."
            export PATH=/usr/local/go/bin:$PATH
            go version

            echo "🔧 Building Go app..."
            go build -o app

            echo "🚀 Restarting service..."
            pkill app || true
            nohup ./app > log.txt 2>&1 &

            
